services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - /docker/appdata/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
