services:
  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    network_mode: bridge
    ports:
      - 7878:7878
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker-configs/radarr:/config
      - /mnt/data/docker-data:/data
  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    network_mode: bridge
    ports:
      - 8989:8989
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker-configs/sonarr:/config
      - /mnt/data/docker-data:/data
  bazarr:
    container_name: bazarr
    image: ghcr.io/hotio/bazarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    network_mode: bridge
    ports:
      - 6767:6767
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker-configs/bazarr:/config
      - /mnt/data/docker-data/media:/data/media
  flaresolverr:
    container_name: flaresolverr
    image: ghcr.io/flaresolverr/flaresolverr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    network_mode: bridge
    environment:
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/Amsterdam
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8191:8191
  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    network_mode: bridge
    ports:
      - 9696:9696
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker-configs/prowlarr:/config
  qbittorrent:
    image: ghcr.io/hotio/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    logging:
      driver: json-file
    network_mode: bridge
    ports:
      - 8080:8080
    volumes:
      - /docker-configs/qbittorrent:/config
      - /mnt/data/docker-data/torrents:/data/torrents
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - WEBUI_PORTS=8080
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    restart: unless-stopped
    logging:
      driver: json-file
    network_mode: bridge
    ports:
      - 5055:5055
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /docker-configs/overseerr:/app/config
  sabnzbd:
    image: ghcr.io/hotio/sabnzbd:latest
    container_name: sabnzbd
    restart: unless-stopped
    logging:
      driver: json-file
    network_mode: bridge
    ports:
      - 8081:8080
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker-configs/sabnzbd:/config
      - /docker-data/sabnzbd-cache:/data/cache # Your incomplete downloads should download to an SSD for faster unpacking speeds
      - /mnt/data/docker-data/usenet:/data/usenet
  plex:
    image: ghcr.io/hotio/plex:latest
    container_name: plex
    restart: unless-stopped
    logging:
      driver: json-file
    network_mode: bridge
    ports:
      - 32400:32400
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker-configs/plex:/config
      - /mnt/data/docker-data/media:/data/media
      - /tmp/plex:/transcode
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - PLEX_CLAIM_TOKEN=${PLEX_CLAIM_TOKEN}
  tautulli:
    image: ghcr.io/hotio/tautulli
    container_name: tautulli
    restart: unless-stopped
    logging:
      driver: json-file
    network_mode: bridge
    ports:
      - 8181:8181
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker-configs/tautulli:/config
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    network_mode: bridge
    restart: unless-stopped
    logging:
      driver: json-file
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --schedule "0 0 3 * * *"
