services:
  node_exporter:
      image: quay.io/prometheus/node-exporter:latest
      container_name: node_exporter
      command:
        - '--path.rootfs=/host'
      ports:
        - 9100:9100
      pid: host
      restart: unless-stopped
      volumes:
        - '/:/host:ro,rslave'
  cadvisor:
      image: gcr.io/cadvisor/cadvisor:v0.50.0
      container_name: cadvisor
      ports:
        - 9101:8080
      volumes:
        - /:/rootfs:ro
        - /run:/run:ro
        - /sys:/sys:ro
        - /var/lib/docker/:/var/lib/docker:ro
        - /dev/disk/:/dev/disk:ro
      devices:
        - /dev/kmsg
      privileged: true
      restart: unless-stopped
